spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: ${DB_PASS:password}
    maxPoolSize: ${DB_MAX_POOL_SIZE:10}
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      "liquibase": info
