spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    maxPoolSize: 10
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      "liquibase": debug
